name: Run Selenium Java Tests

on:
  schedule:
  - cron: '/2 * * * *'  # Runs every day at 00:50 AM IST
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: windows-latest  # Running on Windows since it's chromedriver-win64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'  # Update if needed

      - name: Install Google Chrome
        run: choco install googlechrome --ignore-checksum -y

      - name: Set ChromeDriver Path
        run: echo "${{ github.workspace }}\Driver\Chrome Driver\chromedriver-win64" >> $GITHUB_PATH

      - name: Verify ChromeDriver Version
        run: |
          $chromeDriverPath = "${{ github.workspace }}\Driver\Chrome Driver\chromedriver-win64\chromedriver.exe"
          & $chromeDriverPath --version

      - name: Run Selenium Tests
        run: mvn test --fail-never  # Prevents pipeline failure and ensures reports are generated


      - name: Debug Test Reports Location
        run: |
          echo "Checking Test Reports..."
          if (Test-Path "target\test-output\") { echo "TestNG reports found"; Get-ChildItem "target\test-output\" }
          else { echo "No test reports found!" }

      - name: Display Test Results
        if: always()
        run: |
          if (Test-Path "target\test-output\") { type target\test-output\abc.txt }
          else { echo "No test reports found!" }

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: |
            target/test-output/
          if-no-files-found: ignore  # Avoid pipeline failure if reports are missing
