name: Run Selenium Java Tests

on:
  schedule:
    - cron: '0 9 * * *'  # Runs every day at 9 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  test:
    runs-on: windows-latest  # Running on Windows since it's chromedriver-win64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'  # Update if needed

      - name: Install Google Chrome
        run: choco install googlechrome --ignore-checksum -y

      - name: Set ChromeDriver Path
        run: echo "${{ github.workspace }}\Driver\Chrome Driver\chromedriver-win64" >> $GITHUB_PATH

      - name: Verify ChromeDriver Version
        run: |
          $chromeDriverPath = "${{ github.workspace }}\Driver\Chrome Driver\chromedriver-win64\chromedriver.exe"
          & $chromeDriverPath --version

      - name: Run Selenium Tests
        run: mvn test  # Runs the test suite

      - name: Display Test Results
        if: always()  # Always runs even if tests fail
        run: type target\surefire-reports\*.txt  # Display test results

      - name: Upload Test Report (JUnit or TestNG)
        if: always()  # Upload reports even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: Test-Reports
          path: target/surefire-reports/  # Change if using a different test report path
